# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a91a0663b456e574610f35f0dc5e12a872fb85b023b9d73d1a5dfe6fb703bb09aa05d596424e09060c900ec0d6bb9a17687f07d24004ad546003cf8a562b7b01

test:
  secret_key_base: 88001303ac8c9ad971cca1ee4cd2e7399a973aeab8d32a91992a2d784ed824582f00b19e5a39c44ab691a2f792541143cbb9d610f5487c0544c192f7ec5b183c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
